feat: added response conversion node
kyma-project/kyma-companion pull request #318
Opened 2024-12-23 10:29 UTC by tanweersalah

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2025-01-21 08:22 UTC, muralov commented on src/agents/common/response_converter.py
> +        return parsed_yaml
let's use TypedDict or Pydantic to parse:
```
class YAMLMetadata(TypedDict):
    namespace: str
    name: str

class YAMLConfig(TypedDict):
    metadata: YAMLMetadata
    kind: str

def _parse_yamls(self, yaml_config: str) -> Optional[YAMLConfig]:
    """
    Parse YAML string into Python object with error handling.
    Returns None if parsing fails.

    Args:
        yaml_config: YAML configuration string

    Returns:
        Parsed YAML object or None if parsing fails
    
    Example:
        >>> result = converter._parse_yamls("```yaml\\nkind: Deployment\\n```")
        >>> if result:
        >>>     print(f"Parsed YAML: {result}")
        >>> else:
        >>>     print("Failed to parse YAML")
    """
    try:
        if yaml_config[:7] == "```yaml":
            parsed_yaml = yaml.safe_load(yaml_config[8:-4])
        else:
            parsed_yaml = yaml.safe_load(yaml_config)
        
        return parsed_yaml

    except Exception as e:
        logger.error(
            f"Error while parsing the yaml : {yaml_config} , Exception : {e}"
        )
        return None
   ```

2025-01-21 08:23 UTC, muralov commented on src/agents/common/response_converter.py
> +        return parsed_yaml
As I see if a yaml is generated but doesn't fit the schema, it returns None. 
Have you observed the cases where partial yaml resources are generated? We can discuss this.

2025-01-21 08:30 UTC, muralov commented on src/agents/common/response_converter.py
> +class ResponseConverter:
please create an interface IResponseConverter. That is our convention.

2025-01-21 08:41 UTC, muralov requested changes
Please rebase on main, there is conflict.

I'd add such instructions for prompts so that LLM outputs fit your logic:
```
  1. For new resource deployments, wrap the YAML in <YAML-NEW> </YAML-NEW> tags
  2. For modifications to existing resources, wrap the YAML in <YAML-UPDATE> </YAML-UPDATE> tags
  3. Each YAML configuration must include:
     - apiVersion
     - kind
     - metadata (with at least name and namespace)
  4. Multiple YAML configurations should be separated into individual blocks with appropriate tags
  
    Example:
  <YAML-NEW>
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-new-app
    namespace: default
  spec:
    ...
  </YAML-NEW>

  <YAML-UPDATE>
  apiVersion: v1
  kind: Service
  metadata:
    name: existing-service
    namespace: production
  spec:
    ...
  </YAML-UPDATE>
 ```

2025-01-23 15:41 UTC, tanweersalah commented on src/agents/supervisor/agent.py
i dont see either of them , 

https://langfuse.mur-nats.kymatunas.shoot.canary.k8s-hana.ondemand.com/project/cm4ty39mm000bifl0he3e61er/traces/1b0fd170-809b-47aa-82b7-b233a06db29b?timestamp=2025-01-23T15%3A34%3A09.422Z&observation=ca1b5345-a54d-4296-a05b-429fee764a86

2025-01-24 04:48 UTC, muralov approved these changes

2025-01-24 04:50 UTC, merged