chore: Add reranker integration tests
kyma-project/kyma-companion pull request #319
Opened 2024-12-23 14:33 UTC by marcobebway

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2025-01-13 08:56 UTC, friedrichwilken requested changes

2025-01-13 08:56 UTC, friedrichwilken commented on src/rag/reranker/reranker.py
> +        If the RRF filtration is enabled:
does RRF stand for the reciprocal rank fusion algorithm?

2025-01-13 08:56 UTC, friedrichwilken commented on tests/integration/rag/test_reranker.py
> +        # TODO: Increase the threshold.
How is this a TODO and when to we do this?

2025-01-13 09:12 UTC, marcobebway commented on src/rag/reranker/reranker.py
> +        If the RRF filtration is enabled:
I updated the doc to make it more clear.

2025-01-13 09:12 UTC, marcobebway commented on tests/integration/rag/test_reranker.py
> +        # TODO: Increase the threshold.
Updated.

2025-01-13 09:34 UTC, friedrichwilken commented on tests/integration/rag/test_reranker.py
> +        # TODO: Increase the threshold.
Thanks!

2025-01-13 09:34 UTC, friedrichwilken commented on src/rag/reranker/reranker.py
> +        If the RRF filtration is enabled:
Thanks!

2025-01-13 09:34 UTC, friedrichwilken approved these changes

2025-01-14 10:02 UTC, grego952 approved these changes

2025-01-14 10:03 UTC, merged